server:
  port: 8085

spring:
  mvc:
    view:
      # HTML suffix 설정
      suffix: .html

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정입니다. TRACE Log에 값을 보여줍니다.